
import type { Language, PromptCategory, PromptOptions, PromptGroup, PromptGroupKey, PromptTemplates, Theme } from './types';

const defaultCategories: Record<PromptCategory, string[]> = {
    task: [], articleType: [], role: [], background: [], objective: [], audience: [], theme: [], settingLocation: [], mainSubject: [], characterAction: [], expression: [], clothingAttributes: [], tone: [], perspective: [], timeOfDay: [], weatherConditions: [], lighting: [], colorPalette: [], style: [], movement: [], cameraAngle: [], lensType: [], aspect: [], duration: [], effects: [], negativePrompts: [], complexity: [], resolution: [], renderingEngine: [], length: [], format: [], constraints: [], detailLevel: []
};

export const PROMPT_OPTIONS: PromptOptions = {
  pt: {
    ...defaultCategories,
    task: ["Desenvolvimento de Arquitetura de Software", "Criação de Estratégia de Marketing Digital", "Análise de Dados e Insights de Negócios", "Redação de Documentação Técnica", "Otimização de Algoritmos de Performance", "Criação de Copywriting para Vendas de Alto Ticket", "Planejamento Estratégico de Produto (Roadmap)", "Auditoria de Segurança e Compliance", "Tradução Técnica e Localização", "Desenvolvimento de Aplicações Full-Stack", "Gestão de Crise e Comunicação Corporativa"],
    role: ["Arquiteto de Soluções Senior", "Engenheiro de Machine Learning", "Diretor de Operações (COO)", "Especialista em Cibersegurança", "Consultor Financeiro de Investimentos", "Cientista de Dados e BI", "Product Manager Ágil", "Especialista em SEO e Growth Hacking", "Engenheiro de Prompt Profissional", "Estrategista de Marca Senior"],
    background: ["Startup em fase de tração acelerada", "Ambiente corporativo Enterprise (Fortune 500)", "Projeto Acadêmico de Pesquisa Avançada", "Lançamento de Produto Global", "Contexto de Auditoria Regulatória Estrita", "Equipe de Desenvolvimento Remota e Distribuída", "Fusão e Aquisição de Empresas", "Transformação Digital de Negócio Tradicional"],
    length: ["Executivo e Conciso (Sumário)", "Médio e Estruturado (Tópicos)", "Extenso e Profundo (White Paper)", "Formato de Relatório Técnico", "Documento de Especificação Detalhada"],
    format: ["JSON Estruturado", "Markdown Profissional", "Texto Corrido Formal", "Tabelas Comparativas", "Código Comentado"],
    constraints: ["Sem jargões desnecessários", "Focado em eficiência de custos", "Seguindo normas ABNT/APA", "Tom de voz autoritário", "Incluir métricas de sucesso (KPIs)"],
    detailLevel: ["Nível Iniciante", "Nível Profissional", "Nível Expert/C-Level"],
    tone: ["Analítico e Objetivo", "Inspirador e Criativo", "Sério e Diplomático", "Direto e Assertivo", "Empático e Pedagógico"],
  },
  en: {
    ...defaultCategories,
    task: ["Software Architecture Development", "Digital Marketing Strategy Creation", "Data Analysis & Business Insights", "Technical Documentation Writing", "Performance Algorithm Optimization", "High-Ticket Sales Copywriting", "Strategic Product Roadmap Planning", "Security & Compliance Auditing", "Technical Translation & Localization"],
    role: ["Senior Solutions Architect", "Machine Learning Engineer", "Chief Operating Officer (COO)", "Cybersecurity Specialist", "Investment Financial Consultant", "Data Scientist & BI Specialist", "Agile Product Manager", "SEO & Growth Hacking Expert", "Professional Prompt Engineer"],
    background: ["Fast-scaling Startup", "Enterprise Corporate Environment", "Academic Research Project", "Global Product Launch", "Regulatory Audit Context", "Remote Development Team", "Mergers & Acquisitions", "Digital Transformation Project"],
    length: ["Executive & Concise", "Medium & Structured", "Long & Comprehensive", "Technical Report Format", "Detailed Specification Document"],
    format: ["Structured JSON", "Professional Markdown", "Formal Plain Text", "Comparative Tables", "Commented Code"],
    constraints: ["No unnecessary jargon", "Focus on cost efficiency", "Follow APA/Standard guidelines", "Authoritative tone", "Include Success Metrics (KPIs)"],
    detailLevel: ["Beginner Level", "Professional Level", "Expert/C-Level"],
    tone: ["Analytical & Objective", "Inspirational & Creative", "Serious & Diplomatic", "Direct & Assertive", "Empathetic & Pedagogical"],
  },
  fr: { ...defaultCategories, task: ["Développement d'Architecture Logicielle"], role: ["Architecte Solutions Senior"], background: ["Startup en forte croissance"], length: ["Exécutif et Concis"] },
  hi: { ...defaultCategories, task: ["सॉफ्टवेयर आर्किटेक्चर डेवलपमेंट"], role: ["वरिष्ठ समाधान वास्तुकार"], background: ["तेजी से बढ़ती स्टार्टअप"], length: ["कार्यकारी और संक्षिप्त"] },
  ru: { ...defaultCategories, task: ["Разработка программной архитектуры"], role: ["Старший архитектор решений"], background: ["Быстрорастущий стартап"], length: ["Кратко e по делу"] }
};

const commonPhotoTools = {
    photoTitle: "Photo Studio",
    imageAnalyzerTitle: "Analisador de Imagem",
    imageAnalyzerDescription: "Descreva ou faça perguntas sobre qualquer imagem.",
    imageAnalyzerPlaceholder: "O que você quer saber sobre esta foto?",
    imageAnalyzerButton: "Analisar Imagem",
    logoCreatorTitle: "Criador de Logos",
    logoCreatorDescription: "Gere logotipos profissionais para marcas.",
    logoCreatorPlaceholder: "Descreva a marca e o estilo do logo...",
    logoCreatorButton: "Criar Logo",
    captionGeneratorTitle: "Gerador de Legendas",
    captionGeneratorDescription: "Crie legendas criativas para redes sociais.",
    captionGeneratorPlaceholder: "Contexto adicional da foto...",
    captionGeneratorButton: "Gerar Legendas",
    visualStorytellerTitle: "Contador de Histórias",
    visualStorytellerDescription: "Transforme uma foto em uma narrativa curta.",
    visualStorytellerPlaceholder: "Gênero (ex: Fantasia, Noir)...",
    visualStorytellerButton: "Criar História",
    paletteExtractorTitle: "Paleta de Cores",
    paletteExtractorDescription: "Extraia cores dominantes e códigos HEX.",
    paletteExtractorPlaceholder: "Área de foco (opcional)...",
    paletteExtractorButton: "Extrair Paleta",
    textToImageTitle: "Texto para Imagem",
    textToImageDescription: "Gere imagens do zero usando descrições.",
    textToImagePlaceholder: "Uma cidade futurista com luzes neon...",
    textToImageButton: "Gerar Imagem",
    imageColorizerTitle: "Colorizador",
    imageColorizerDescription: "Dê vida a fotos antigas em preto e branco.",
    imageColorizerPlaceholder: "Instruções de cores (opcional)...",
    imageColorizerButton: "Colorir Foto",
    imageRestorerTitle: "Restaurador",
    imageRestorerDescription: "Remova ruídos, rasgos e melhore a nitidez.",
    imageRestorerPlaceholder: "Detalhes do dano (opcional)...",
    imageRestorerButton: "Restaurar Foto",
    cartoonGeneratorTitle: "Efeito Cartoon",
    cartoonGeneratorDescription: "Transforme pessoas em desenhos ou anime.",
    cartoonGeneratorButton: "Transformar em Cartoon",
    dollGeneratorTitle: "Efeito Boneco",
    dollGeneratorDescription: "Transforme fotos em bonecos ou figuras de ação.",
    dollGeneratorButton: "Transformar em Boneco",
    dollHolderTitle: "Mini-Eu",
    dollHolderDescription: "Crie uma imagem segurando sua versão miniatura.",
    dollHolderButton: "Gerar Mini-Eu",
    virtualFittingRoomTitle: "Provador Virtual",
    virtualFittingRoomDescription: "Troque a roupa da pessoa na foto.",
    virtualFittingRoomPlaceholder: "Descreva a nova roupa...",
    virtualFittingRoomButton: "Trocar Roupa",
    bodyShapeChangerTitle: "Ajuste de Corpo",
    bodyShapeChangerDescription: "Modifique a silhueta de forma estética.",
    bodyShapeChangerPlaceholder: "Tipo de corpo...",
    bodyShapeChangerButton: "Ajustar Corpo",
    bodyShapeChangerTypes: ["Ectomorfo", "Mesomorfo", "Atlético", "Curvilíneo", "Definido"],
    wigTryOnTitle: "Troca de Cabelo",
    wigTryOnDescription: "Experimente diferentes perucas e penteados.",
    wigTryOnButton: "Mudar Cabelo",
    objectRemoverTitle: "Remover Objeto",
    objectRemoverDescription: "Apague elementos indesejados da foto.",
    objectRemoverPlaceholder: "O que remover (ex: pessoa no fundo)...",
    objectRemoverButton: "Remover Agora",
    imageExpanderTitle: "Expansor de Imagem",
    imageExpanderDescription: "Crie bordas extras usando IA (Outpainting).",
    imageExpanderButton: "Expandir Imagem",
    backgroundBlurTitle: "Desfoque de Fundo",
    backgroundBlurDescription: "Adicione efeito Bokeh profissional.",
    backgroundBlurButton: "Desfocar Fundo",
    backgroundReplacerTitle: "Troca de Fundo",
    backgroundReplacerDescription: "Mude o cenário de qualquer foto.",
    backgroundReplacerPlaceholder: "Descreva o novo cenário...",
    backgroundReplacerButton: "Trocar Cenário",
    mixMatchTitle: "Mix & Match",
    mixMatchDescription: "Vista uma pessoa com uma roupa de outra foto.",
    mixMatchPersonLabel: "Foto da Pessoa",
    mixMatchClothLabel: "Foto da Roupa",
    mixMatchButton: "Combinar Peças",
    expressionGeneratorTitle: "Gerador de Expressões",
    expressionGeneratorDescription: "Mude o humor do rosto (sorriso, medo, etc).",
    expressionGeneratorButton: "Mudar Expressão",
    paintingGeneratorTitle: "Efeito Pintura",
    paintingGeneratorDescription: "Transforme fotos em obras de arte famosas.",
    paintingGeneratorButton: "Gerar Pintura",
    bnwGeneratorTitle: "Cinematográfico P&B",
    bnwGeneratorDescription: "Filtros preto e branco de alta qualidade.",
    bnwGeneratorButton: "Gerar P&B",
    storybookGeneratorTitle: "Livro de Histórias",
    storybookGeneratorDescription: "Crie um livro infantil baseado no personagem.",
    storybookGeneratorPlaceholder: "Tema da aventura...",
    storybookGeneratorButton: "Criar Livro",
    styleTransformerTitle: "Transformador de Estilo",
    styleTransformerDescription: "Mude a atmosfera da foto (Cyberpunk, etc).",
    styleTransformerButton: "Transformar Estilo",
    styleTransformerStyles: ["Futurista", "Apocalíptico", "Cyberpunk", "Guerra", "Ácido", "Zumbi", "Desértico", "Mad Max", "Stranger Things", "Fantasma", "Blackout"],
    threeDGeneratorTitle: "Foto 3D",
    threeDGeneratorDescription: "Gere efeitos de profundidade e anáglifo.",
    threeDGeneratorButton: "Gerar Efeito 3D",
    threeDObjectGeneratorTitle: "Gerador de Objetos 3D",
    threeDObjectGeneratorDescription: "Crie arquivos .OBJ de baixa poligonalidade.",
    threeDObjectGeneratorImageLabel: "Imagem de Referência",
    threeDObjectGeneratorPlaceholder: "Nome do objeto...",
    threeDObjectGeneratorButton: "Gerar Modelo 3D",
    imageSonifierTitle: "Sonificador",
    imageSonifierDescription: "Converta cores e formas em áudio ambiente.",
    imageSonifierButton: "Ouvir Imagem",
    arFiltersTitle: "Filtros AR",
    arFiltersDescription: "Filtros de rosto em tempo real via webcam.",
    arFiltersStart: "Iniciar Filtros",
    arFiltersStop: "Parar Câmera",
    liquifyTitle: "Editor Liquify",
    liquifyDescription: "Distorção manual de pixels (Warp).",
    liquifyBrushSize: "Tamanho do Pincel",
    liquifyStrength: "Força",
    liquifyReset: "Resetar",
    liquifyDownload: "Baixar Editada",
    manualEnhancerTitle: "Ajuste Manual",
    manualEnhancerDescription: "Controle brilho, contraste e gamma.",
    manualEnhancerBrightness: "Brilho",
    manualEnhancerContrast: "Contraste",
    manualEnhancerGamma: "Gamma",
    manualEnhancerReset: "Reset",
    manualEnhancerDownload: "Baixar",
    sketchToImageTitle: "Sketch para Imagem",
    sketchToImageDescription: "Transforme desenhos em papel em arte digital.",
    sketchToImageStyles: ["Fotorrealista", "3D Render", "Pintura a Óleo", "Ilustração Digital"],
    sketchToImagePlaceholder: "Cores e detalhes extras...",
    sketchToImageButton: "Renderizar Desenho",
    downloadMontage: "Baixar Montagem",
    download: "Baixar",
    error: "Erro na operação.",
    generatingPreview: "Processando..."
};

const commonAiTools = {
    ...commonPhotoTools,
    summarizerLengths: ["Concise", "Medium", "Detailed"],
    summarizerTitle: "Resumidor de Texto",
    summarizerDescription: "Crie resumos rápidos de grandes volumes de texto.",
    summarizerButton: "Resumir",
    articleGeneratorTitle: "Gerador de Artigos",
    articleGeneratorDescription: "Crie artigos profissionais e estruturados.",
    articleGeneratorButton: "Gerar Artigo",
    mathSolverTitle: "Resolução Matemática",
    mathSolverDescription: "Resolva problemas matemáticos passo a passo.",
    mathSolverButton: "Resolver com IA",
    mathSolverLocalButton: "Calcular Local",
    mathSolverModeLocal: "Local",
    mathSolverModeAI: "IA Tutor",
    mathSolverInputLabel: "Problema ou Equação",
    mathSolverPlaceholder: "Ex: 2x + 5 = 15 ou integral de x^2",
    mathSolverImageLabel: "Upload de Foto do Problema",
    mathSolverButtonLoading: "Resolvendo...",
    referenceGeneratorTitle: "Gerador de Referências",
    referenceGeneratorDescription: "Encontre fontes bibliográficas reais para seu tema.",
    referenceGeneratorInputLabel: "Tema ou Frase",
    referenceGeneratorPlaceholder: "Ex: Inteligência Artificial na Medicina",
    referenceGeneratorButton: "Buscar Referências",
    referenceGeneratorButtonLoading: "Buscando...",
    studyGuideTitle: "Guia de Estudos",
    studyGuideDescription: "Transforme notas em um guia estruturado.",
    studyGuideButton: "Gerar Guia",
    studyGuidePlaceholder: "Cole suas notas de aula aqui...",
    academicSourceTitle: "Buscador Acadêmico",
    academicSourceDescription: "Sugestões de bases de dados e termos de busca.",
    academicSourceButton: "Encontrar Fontes",
    academicSourcePlaceholder: "Tema da pesquisa...",
    assignmentAnalyzerTitle: "Analisador de Tarefas",
    assignmentAnalyzerDescription: "Entenda o que o professor realmente quer.",
    assignmentAnalyzerButton: "Analisar",
    assignmentAnalyzerPlaceholder: "Cole o enunciado da tarefa...",
    vocabularyBuilderTitle: "Construtor de Vocabulário",
    vocabularyBuilderDescription: "Crie exercícios de memorização.",
    vocabularyBuilderButton: "Gerar Exercícios",
    vocabularyBuilderPlaceholder: "Lista de palavras ou tema...",
    languagePlanTitle: "Plano de Idiomas",
    languagePlanDescription: "Desafio de 30 dias para aprender.",
    languagePlanButton: "Gerar Plano",
    languagePlanPlaceholder: "Idioma e nível desejado...",
    pdfSummarizerTitle: "Resumidor de PDF",
    pdfSummarizerDescription: "Analise documentos PDF complexos.",
    pdfSummarizerButton: "Resumir PDF",
    pdfSummarizerPlaceholder: "Instruções específicas...",
    videoToPdfTitle: "Vídeo para Estudo",
    videoToPdfDescription: "Transforme vídeos em guias imprimíveis.",
    videoToPdfButton: "Gerar PDF",
    videoToPdfPlaceholder: "URL do YouTube...",
    videoToPdfInputLabel: "Link do Vídeo",
    textHumanizerTitle: "Humanizador de Texto",
    textHumanizerDescription: "Torne textos de IA mais naturais.",
    textHumanizerButton: "Humanizar",
    textHumanizerPlaceholder: "Texto gerado por IA...",
    mindMapTitle: "Mapa Mental (Mermaid)",
    mindMapDescription: "Gere código para visualização lógica.",
    mindMapButton: "Gerar Código",
    mindMapPlaceholder: "Tema central do mapa...",
    routePlannerTitle: "Planejador de Rotas",
    routePlannerDescription: "Rotas inteligentes com paradas.",
    routePlannerButton: "Gerar Rota",
    routePlannerOrigin: "Origem",
    routePlannerDestination: "Destino",
    routePlannerStops: "Paradas (opcional)",
    gameAssetsTitle: "Assets para Jogos",
    gameAssetsDescription: "Gere arte conceitual ou lore.",
    gameAssetsButton: "Gerar Asset",
    gameAssetsTypeLabel: "Tipo de Asset",
    gameAssetsPlaceholder: "Descrição do personagem ou mundo...",
    gameAssetsTypes: ["Personagem (Imagem)", "Narrativa (Texto)"],
    htmlGeneratorTitle: "Gerador de HTML",
    htmlGeneratorDescription: "Crie páginas web prontas para uso.",
    htmlGeneratorButton: "Gerar Código",
    htmlGeneratorPlaceholder: "Descreva a página (ex: Landing page de café)...",
    interviewPrepTitle: "Preparação de Entrevista",
    interviewPrepDescription: "Perguntas e respostas baseadas no cargo.",
    interviewPrepButton: "Preparar",
    interviewPrepPlaceholder: "Descrição da vaga ou cargo...",
    emailWriterTitle: "Gerador de E-mails",
    emailWriterDescription: "E-mails profissionais em segundos.",
    emailWriterButton: "Gerar E-mail",
    emailWriterRecipient: "Destinatário",
    emailWriterTone: "Tom",
    emailWriterPoints: "Pontos principais",
    resumeGeneratorTitle: "Gerador de Currículo",
    resumeGeneratorDescription: "Crie currículos em HTML/DOC.",
    resumeGeneratorButton: "Gerar Currículo",
    resumeGeneratorName: "Nome Completo",
    resumeGeneratorRole: "Cargo Pretendido",
    resumeGeneratorExperience: "Experiência",
    resumeGeneratorSkills: "Habilidades",
    resumeGeneratorEducation: "Formação",
    abntFormatterTitle: "Formatador ABNT",
    abntFormatterDescription: "Formate textos seguindo normas técnicas.",
    abntFormatterButton: "Formatar",
    abntFormatterPlaceholder: "Cole o texto para formatar...",
    financialAdvisorTitle: "Consultor Financeiro",
    financialAdvisorDescription: "Planos de impostos e lucros.",
    financialAdvisorButton: "Gerar Plano",
    financialAdvisorTypeLabel: "Tipo de Consulta",
    financialAdvisorPlaceholder: "Contexto financeiro...",
    financialAdvisorTypes: ["Imposto de Renda", "Plano de Vendas", "Reserva de Emergência"],
    legalAssistantTitle: "Assistente Jurídico",
    legalAssistantDescription: "Análise de contratos e checklists.",
    legalAssistantButton: "Analisar",
    legalAssistantTypeLabel: "Serviço",
    legalAssistantPlaceholder: "Conteúdo do contrato ou regras...",
    legalAssistantTypes: ["Analisar Contrato", "Checklist de Aprovação"],
    dataAnalyzerTitle: "Analisador de Dados",
    dataAnalyzerDescription: "Insights de vendas e comportamento.",
    dataAnalyzerButton: "Analisar Dados",
    dataAnalyzerPlaceholder: "Cole seus dados brutos aqui...",
    socialMediaTitle: "Social Media Planner",
    socialMediaDescription: "Calendário editorial e estratégia.",
    socialMediaButton: "Gerar Plano",
    socialMediaPlaceholder: "Descrição do negócio...",
    topicSimplifierTitle: "Simplificador",
    topicSimplifierDescription: "Explique temas complexos para leigos.",
    topicSimplifierButton: "Simplificar",
    topicSimplifierPlaceholder: "Tema complexo...",
    realTimeSearchTitle: "Busca em Tempo Real",
    realTimeSearchDescription: "Pesquisa na web via Gemini 3.",
    realTimeSearchButton: "Pesquisar",
    realTimeSearchPlaceholder: "O que deseja saber hoje?",
    realTimeSearchButtonLoading: "Pesquisando...",
    researchAssistantTitle: "Assistente de Pesquisa",
    researchAssistantDescription: "Sumários e fontes rápidas.",
    researchAssistantButton: "Pesquisar",
    researchAssistantInputLabel: "Tema da Pesquisa",
    researchAssistantPlaceholder: "Ex: Impacto do 5G na indústria...",
    citationGeneratorTitle: "Gerador de Citações",
    citationGeneratorDescription: "Citações rápidas em vários estilos.",
    citationGeneratorButton: "Gerar",
    citationGeneratorStyles: ["APA", "ABNT", "MLA", "Vancouver"],
    citationGeneratorAuthorsLabel: "Autores",
    citationGeneratorTitleLabel: "Título",
    citationGeneratorYearLabel: "Ano",
    citationGeneratorSourceLabel: "Fonte/Editora",
    bibliographyOrganizerTitle: "Organizador de Bibliografia",
    bibliographyOrganizerDescription: "Ordene suas referências.",
    bibliographyOrganizerButton: "Organizar",
    bibliographyOrganizerStyles: ["APA", "ABNT", "Chicago"],
    bibliographyOrganizerInputLabel: "Lista de Fontes",
    autoEnhancerTitle: "Auto Enhancer",
    autoEnhancerDescription: "Aprimoramento automático de fotos.",
    autoEnhancerButton: "Aprimorar",
    autoEnhancerOptions: {
        blemishes: "Remover Manchas",
        smile: "Adicionar Sorriso",
        skinTone: "Tom de Pele",
        oiliness: "Reduzir Oleosidade",
        lighting: "Iluminação Studio",
        makeup: "Grooming IA",
        wrinkles: "Suavizar Rugas",
        sharpen: "Nitidez HD"
    },
    portfolioAdvisorTitle: "Investment Advisor",
    portfolioAdvisorDescription: "Sugestão de carteira diversificada.",
    portfolioAdvisorButton: "Gerar Carteira",
    portfolioAdvisorButtonLoading: "Analisando...",
    portfolioAdvisorProfileLabel: "Perfil",
    portfolioAdvisorProfiles: ["Conservador", "Moderado", "Arrojado"],
    portfolioAdvisorTimeHorizonLabel: "Prazo",
    portfolioAdvisorTimeHorizons: ["Curto (1 ano)", "Médio (5 anos)", "Longo (10+ anos)"],
    portfolioAdvisorAmountLabel: "Valor Investido",
    portfolioAdvisorShowTrending: "Ver Tendências",
    trendingAssetsModal: {
      title: "Tendências de Mercado",
      loading: "Buscando dados reais...",
      disclaimer: "Aviso: Isto não é recomendação de investimento.",
      close: "Fechar",
      downloadPdf: "Baixar PDF"
    }
};

export const UI_LABELS: Record<Language, any> = {
  pt: {
    title: "Visionary AI Suite", generatorTab: "Prompt Builder", toolsTab: "IA Utilitários", photosTab: "Photo Studio", makeupTab: "IA Makeup", videoTab: "Video Suite", socialTab: "IA Social", wikiTab: "Wiki Research", editorTab: "Camadas", communityTab: "Comunidade",
    optionsTitle: "Parâmetros Profissionais", generatedJsonTitle: "Prompt JSON Resultante", searchPlaceholder: "Pesquisar...", sitemap: "Mapa",
    takePhoto: "Usar Câmera", cancel: "Cancelar", switchCamera: "Inverter", credit: "Por Elias Lopes / TechViva",
    theme: "Tema Visual",
    themes: { dark: "Modo Escuro", light: "Modo Claro", 'high-contrast': "Alto Contraste", deuteranopia: "Daltônico (G)", protanopia: "Daltônico (R)", tritanopia: "Daltônico (B)" },
    errors: {
      api: "Falha na comunicação com Gemini 3. Verifique sua chave API.",
      camera: "Câmera indisponível.",
      network: "Erro de conexão.",
      safety: "Conteúdo bloqueado pelos filtros de segurança.",
      unknown: "Erro inesperado."
    },
    customTextLabels: { label: "Instruções Específicas", placeholder: "Adicione detalhes extras..." },
    resultTitle: "Resultado da IA",
    generatingPreview: "IA está trabalhando..."
  },
  en: {
    title: "Visionary AI Suite", generatorTab: "Prompt Builder", toolsTab: "AI Utilities", photosTab: "Photo Studio", makeupTab: "AI Makeup", videoTab: "Video Suite", socialTab: "AI Social", wikiTab: "Wiki Research", editorTab: "Layers", communityTab: "Community",
    optionsTitle: "Professional Parameters", generatedJsonTitle: "Resulting JSON Prompt", searchPlaceholder: "Search...", sitemap: "Sitemap",
    takePhoto: "Use Camera", cancel: "Cancel", switchCamera: "Switch", credit: "By Elias Lopes / TechViva",
    theme: "Visual Theme",
    themes: { dark: "Dark Mode", light: "Light Mode", 'high-contrast': "High Contrast", deuteranopia: "Color Blind (G)", protanopia: "Color Blind (R)", tritanopia: "Color Blind (B)" },
    errors: {
      api: "Gemini 3 communication failure. Check API Key.",
      camera: "Camera unavailable.",
      network: "Network error.",
      safety: "Content blocked by safety filters.",
      unknown: "Unexpected error."
    },
    customTextLabels: { label: "Specific Instructions", placeholder: "Add extra details..." },
    resultTitle: "AI Result",
    generatingPreview: "AI is working..."
  },
  fr: { title: "Visionary AI Suite", generatorTab: "Prompt Builder", toolsTab: "IA Outils", photosTab: "Photo Studio", makeupTab: "IA Makeup", videoTab: "Video Suite", socialTab: "IA Social", wikiTab: "Wiki Research", editorTab: "Calques", communityTab: "Communauté", sitemap: "Sitemap", credit: "Par Elias Lopes / TechViva", themes: {}, errors: {}, customTextLabels: {} },
  hi: { title: "Visionary AI Suite", generatorTab: "प्रॉम्प्ट बिल्डर", toolsTab: "AI उपयोगिताएँ", photosTab: "फोटो स्टूडियो", makeupTab: "AI मेकअप", videoTab: "वीडियो सुitet", socialTab: "AI सोशल", wikiTab: "विकी रिसर्च", editorTab: "परतें", communityTab: "समुदाय", sitemap: "साइटमैप", credit: "एलियाas लोपेज / TechViva द्वारा", themes: {}, errors: {}, customTextLabels: {} },
  ru: { title: "Visionary AI Suite", generatorTab: "Конструктор промптов", toolsTab: "ИИ Утилиты", photosTab: "Фотостудия", makeupTab: "ИИ Макияж", videoTab: "Видео Сюита", socialTab: "ИИ Соцсети", wikiTab: "Вики Исследование", editorTab: "Слои", communityTab: "Сообщество", sitemap: "Карта сайта", credit: "Элиас Лопес / TechViva", themes: {}, errors: {}, customTextLabels: {} }
};

export const AI_TOOLS_LABELS: Record<Language, any> = {
  pt: { ...commonAiTools, error: "Falha na operação Gemini 3", resultTitle: "Relatório de IA", generatingPreview: "Analisando com Gemini 3...", download: "Baixar", takePhoto: "Abrir Câmera" },
  en: { ...commonAiTools, error: "Gemini 3 Operation Failed", resultTitle: "AI Report", generatingPreview: "Analyzing with Gemini 3...", download: "Download", takePhoto: "Open Camera" },
  fr: { ...commonAiTools, error: "Échec Gemini 3", resultTitle: "Résultat", generatingPreview: "IA trabalha...", download: "Télécharger", takePhoto: "Ouvrir Caméra" },
  hi: { ...commonAiTools, error: "Gemini 3 विफल", resultTitle: "परिणाम", generatingPreview: "IA काम कर रहा है...", download: "डाउनलोड", takePhoto: "कैmra खोलें" },
  ru: { ...commonAiTools, error: "Сбой Gemini 3", resultTitle: "Результат", generatingPreview: "ИИ работает...", download: "Скачать", takePhoto: "Открыть câmera" }
};

export const CATEGORY_LABELS: Record<Language, Record<PromptCategory, string>> = {
  pt: { task: "Tarefa Corporativa", role: "Persona/Cargo", background: "Contexto de Negócio", length: "Extensão", format: "Formato de Saída", constraints: "Restrições Legais/Regras", detailLevel: "Nível de Detalhe", tone: "Tom de Voz", perspective: "Perspectiva", articleType: "Tipo", objective: "Objetivo", audience: "Público", theme: "Tema", settingLocation: "Local", mainSubject: "Sujeito", characterAction: "Ação", expression: "Expressão", clothingAttributes: "Traje", timeOfDay: "Hora", weatherConditions: "Clima", lighting: "Iluminação", colorPalette: "Paleta", style: "Estilo", movement: "Movimento", cameraAngle: "Ângulo", lensType: "Lente", aspect: "Proporção", duration: "Duração", effects: "Efeitos", negativePrompts: "Negativos", complexity: "Complexity", resolution: "Resolução", renderingEngine: "Render" },
  en: { task: "Corporate Task", role: "Persona/Role", background: "Business Context", length: "Length", format: "Output Format", constraints: "Constraints/Rules", detailLevel: "Detail Level", tone: "Voice Tone", perspective: "Perspective", articleType: "Type", objective: "Objective", audience: "Audience", theme: "Theme", settingLocation: "Location", mainSubject: "Subject", characterAction: "Action", expression: "Expression", clothingAttributes: "Clothing", timeOfDay: "Time", weatherConditions: "Weather", lighting: "Lighting", colorPalette: "Palette", style: "Style", movement: "Movement", cameraAngle: "Angle", lensType: "Lens", aspect: "Aspect", duration: "Duration", effects: "Effects", negativePrompts: "Negative", complexity: "Complexity", resolution: "Resolution", renderingEngine: "Render" },
  fr: { ...defaultCategories, task: "Tâche" } as any,
  hi: { ...defaultCategories, task: "कार्य" } as any,
  ru: { ...defaultCategories, task: "Задача" } as any
};

export const WIKI_TOOLS_LABELS: Record<Language, any> = {
    pt: { 
        title: "Wiki Research",
        description: "Ferramentas profissionais para editores e pesquisadores da Wikipédia.",
        citationFinderTitle: "Validador de Citações", 
        citationFinderDescription: "Verifique fatos e encontre fontes confiáveis.",
        citationFinderButton: "Validar com Gemini 3",
        searching: "Buscando fontes...", 
        wikitextTitle: "Conversor Wikitext",
        wikitextDescription: "Converta texto simples para sintaxe MediaWiki.",
        wikitextButton: "Gerar Wikitext",
        wikitextPlaceholder: "Cole o texto para converter...",
        wikidataTitle: "Extrator Wikidata",
        wikidataDescription: "Extraia triplas de dados estruturados para o Wikidata.",
        wikidataButton: "Extrair Dados",
        wikidataPlaceholder: "Biografia ou texto de fatos...",
        wikidataModeLabel: "Modo de Saída",
        wikidataModes: { human: "Leitura Humana", quickstatements: "QuickStatements (Bot)" },
        sparqlTitle: "Gerador SPARQL",
        sparqlDescription: "Crie consultas complexas para o Wikidata Query Service.",
        sparqlButton: "Gerar Query",
        sparqlPlaceholder: "Ex: Pintores brasileiros nascidos em Paris...",
        sparqlRunButton: "Executar na Web",
        sparqlResultsTitle: "Resultados da Consulta",
        sparqlError: "Erro na Query",
        stubTitle: "Gerador de Esboços",
        stubDescription: "Crie a estrutura inicial de um artigo neutro.",
        stubButton: "Gerar Esboço",
        stubPlaceholder: "Fatos e tópicos do artigo...",
        running: "Executando...",
        noResults: "Nenhum resultado encontrado.",
        openQuickStatements: "Abrir QuickStatements",
        helpModal: { title: "Ajuda Wiki", qTitle: "Entidades (Q)", qDesc: "IDs de itens no Wikidata.", qExample: "Ex: Q42 (Douglas Adams)", pTitle: "Propriedades (P)", pDesc: "Atributos das entidades.", pExample: "Ex: P106 (Ocupação)" }
    },
    en: { 
        title: "Wiki Research", 
        description: "Professional tools for Wikipedia editors and researchers.",
        citationFinderTitle: "Citation Validator", 
        citationFinderDescription: "Verify facts and find reliable sources.",
        citationFinderButton: "Validate with Gemini 3",
        searching: "Searching sources...", 
        wikitextTitle: "Wikitext Converter",
        wikitextDescription: "Convert plain text to MediaWiki syntax.",
        wikitextButton: "Generate Wikitext",
        wikitextPlaceholder: "Paste text to convert...",
        wikidataTitle: "Wikidata Extractor",
        wikidataDescription: "Extract structured data triples for Wikidata.",
        wikidataButton: "Extract Data",
        wikidataPlaceholder: "Biography or fact-based text...",
        wikidataModeLabel: "Output Mode",
        wikidataModes: { human: "Human Readable", quickstatements: "QuickStatements (Bot)" },
        sparqlTitle: "SPARQL Generator",
        sparqlDescription: "Create complex queries for Wikidata Query Service.",
        sparqlButton: "Generate Query",
        sparqlPlaceholder: "Ex: Brazilian painters born in Paris...",
        sparqlRunButton: "Run on Web",
        sparqlResultsTitle: "Query Results",
        sparqlError: "Query Error",
        stubTitle: "Stub Generator",
        stubDescription: "Create the initial structure of a neutral article.",
        stubButton: "Generate Stub",
        stubPlaceholder: "Facts and topics for the article...",
        running: "Running...",
        noResults: "No results found.",
        openQuickStatements: "Open QuickStatements",
        helpModal: { title: "Wiki Help", qTitle: "Entities (Q)", qDesc: "Wikidata Item IDs.", qExample: "Ex: Q42 (Douglas Adams)", pTitle: "Properties (P)", pDesc: "Entity attributes.", pExample: "Ex: P106 (Occupation)" }
    },
    fr: { title: "Wiki Research", citationFinderTitle: "Validateur", searching: "Recherche...", citationFinderButton: "Valider", wikidataModes: { human: "Humain", quickstatements: "Bot" }, helpModal: { title: "Aide Wiki" } },
    hi: { title: "Wiki Research", citationFinderTitle: "सत्यापनकर्ता", searching: "खोज रहा है...", citationFinderButton: "सत्यापित करें", wikidataModes: { human: "मानव", quickstatements: "बॉट" }, helpModal: { title: "विकी मदद" } },
    ru: { title: "Wiki Research", citationFinderTitle: "Валидатор", searching: "Поиск...", citationFinderButton: "Проверить", wikidataModes: { human: "Человек", quickstatements: "Бот" }, helpModal: { title: "Вики Помощь" } }
};

export const PROMPT_GROUPS: PromptGroup[] = [
    { id: 'coreContext', categories: ['task', 'role', 'background', 'length'] },
    { id: 'outputConstraints', categories: ['format', 'constraints', 'detailLevel', 'tone'] },
];

export const GROUP_LABELS: Record<Language, Record<PromptGroupKey, string>> = {
    pt: { coreContext: "Estrutura do Negócio", subjectDetails: "Detalhes do Sujeito", sceneSetup: "Cenário", cinematography: "Câmera e Luz", postProduction: "Estilo e Efeitos", outputConstraints: "Regras de Entrega" },
    en: { coreContext: "Business Structure", subjectDetails: "Subject Details", sceneSetup: "Scene", cinematography: "Camera & Light", postProduction: "Style & Effects", outputConstraints: "Delivery Rules" },
    fr: { coreContext: "Structure", subjectDetails: "Détails", sceneSetup: "Scène", cinematography: "Caméra", postProduction: "Style", outputConstraints: "Règles" },
    hi: { coreContext: "संरचना", subjectDetails: "विवरण", sceneSetup: "दृश्य", cinematography: "कैमरा", postProduction: "शैली", outputConstraints: "नियम" },
    ru: { coreContext: "Структура", subjectDetails: "Детали", sceneSetup: "Сцена", cinematography: "Камера", postProduction: "Стиль", outputConstraints: "Правила" }
};

export const MAKEUP_TOOLS_LABELS: Record<Language, any> = {
    pt: { 
        title: "Makeup Studio", description: "Retoque Facial por IA Profissional", faces: { main: "Principal", all: "Todos", left: "Esquerdo", right: "Direito" }, 
        faceSelect: "Selecionar Rosto", color: "Cor do Efeito", intensity: "Intensidade", applying: "Aplicando...", apply: "Aplicar Efeito",
        tools: { lipstick: "Batom", blush: "Blush", foundation: "Base", contour: "Contorno", whitening: "Dentes", slim: "Afinar", autoFix: "Auto", eyes: "Olhos", eyeshadow: "Sombra", eyeliner: "Delineador", lashes: "Cílios", nose: "Nariz", acne: "Manchas", wrinkles: "Rugas", openEyes: "Abrir Olhos", smile: "Sorriso", brightness: "Luz", sharpen: "Nitidez", wig: "Peruca", hat: "Chapéu", hairColor: "Cor Cabelo", removeBg: "Fundo", tan: "Bronzeado" } 
    },
    en: { 
        title: "Makeup Studio", description: "Professional AI Face Retouching", faces: { main: "Main", all: "All", left: "Left", right: "Right" }, 
        faceSelect: "Select Face", color: "Effect Color", intensity: "Intensity", applying: "Applying...", apply: "Apply Effect",
        tools: { lipstick: "Lipstick", blush: "Blush", foundation: "Foundation", contour: "Contour", whitening: "Teeth", slim: "Slim", autoFix: "Auto", eyes: "Eyes", eyeshadow: "Eyeshadow", eyeliner: "Eyeliner", lashes: "Lashes", nose: "Nose", acne: "Acne", wrinkles: "Wrinkles", openEyes: "Open Eyes", smile: "Smile", brightness: "Brightness", sharpen: "Sharpen", wig: "Wig", hat: "Hat", hairColor: "Hair Color", removeBg: "BG", tan: "Tan" } 
    },
    fr: { title: "Makeup Studio", description: "Retouche", faces: { main: "Principal" }, tools: {} }, hi: { title: "Makeup Studio", description: "메कअप", faces: { main: "मुख्य" }, tools: {} }, ru: { title: "Makeup Studio", description: "Макияж", faces: { main: "Главный" } }
};

export const VIDEO_TOOLS_LABELS: Record<Language, any> = {
    pt: { 
        title: "Video Suite", description: "Edição de Vídeo Assistida por IA", fetchInfo: "Analisar Vídeo", downloadNow: "Baixar", duration: "Duração", sourceFormat: "De", targetFormat: "Para", convertTo: "Converter para", videoDownloaderTitle: "Downloader", converterWasmTitle: "Conversor Local",
        audioVisualizerTitle: "Visualizador Áudio", vocalRemoverTitle: "Remover Vocal", avatarTalkerTitle: "Avatar Falante", cropperTitle: "Recortar Vídeo", quoteVideoTitle: "Vídeo de Citação", captionerTitle: "Gerador de Legendas", transcriberTitle: "Transcrição Vídeo", ideatorTitle: "IA Ideator", converterTitle: "Script Conversor",
        serverDownloadDirect: "Servidor Direto", serverDownloadScript: "Gerar Script", downloadModeLabel: "Modo", downloadModeVideo: "Vídeo + Áudio", downloadModeAudio: "Apenas Áudio", scriptTypeLabel: "Linguagem Script", generating: "Gerando...", generate: "Gerar Agora", qualityLabel: "Qualidade", qualityHigh: "Alta (8Mbps)", qualityMedium: "Média (2.5Mbps)", qualityLow: "Baixa (0.8Mbps)", startCrop: "Iniciar Recorte", stopCrop: "Parar Gravador", cropComplete: "Recorte Finalizado!", quotePlaceholder: "Digite a citação aqui...", authorPlaceholder: "Autor (opcional)", startRender: "Gerar Vídeo", rendering: "Renderizando...", avatarGenderLabel: "Gênero Avatar", male: "Masculino", female: "Feminino", textToSpeak: "Texto para Falar", voice: "Voz do Sistema", pitch: "Tom", rate: "Velocidade", speak: "Falar", stop: "Parar", vocalRemoverProcessing: "Processando Áudio...", vocalRemoverDownload: "Baixar Instrumental", vocalRemoverPlayOriginal: "Áudio Original", vocalRemoverPlayInstrumental: "Resultado (Karaokê)", startVisualizer: "Iniciar Microfone", stopVisualizer: "Parar Captura"
    },
    en: { 
        title: "Video Suite", description: "AI-Assisted Video Edition", fetchInfo: "Analyze Video", downloadNow: "Download", duration: "Duration", sourceFormat: "From", targetFormat: "To", convertTo: "Convert to", videoDownloaderTitle: "Downloader", converterWasmTitle: "Local Converter",
        audioVisualizerTitle: "Audio Visualizer", vocalRemoverTitle: "Vocal Remover", avatarTalkerTitle: "Avatar Talker", cropperTitle: "Video Cropper", quoteVideoTitle: "Quote to Video", captionerTitle: "Caption Generator", transcriberTitle: "Video Transcription", ideatorTitle: "AI Ideator", converterTitle: "Converter Script",
        serverDownloadDirect: "Server Direct", serverDownloadScript: "Generate Script", downloadModeLabel: "Mode", downloadModeVideo: "Video + Audio", downloadModeAudio: "Audio Only", scriptTypeLabel: "Script Language", generating: "Generating...", generate: "Generate Now", qualityLabel: "Quality", qualityHigh: "High (8Mbps)", qualityMedium: "Medium (2.5Mbps)", qualityLow: "Low (0.8Mbps)", startCrop: "Start Crop", stopCrop: "Stop Recorder", cropComplete: "Crop Finished!", quotePlaceholder: "Type quote here...", authorPlaceholder: "Author (optional)", startRender: "Render Video", rendering: "Rendering...", avatarGenderLabel: "Avatar Gender", male: "Male", female: "Female", textToSpeak: "Text to Speak", voice: "System Voice", pitch: "Pitch", rate: "Rate", speak: "Speak", stop: "Stop", vocalRemoverProcessing: "Processing Audio...", vocalRemoverDownload: "Download Instrumental", vocalRemoverPlayOriginal: "Original Audio", vocalRemoverPlayInstrumental: "Result (Karaoke)", startVisualizer: "Start Microphone", stopVisualizer: "Stop Capture"
    },
    fr: { title: "Video Suite", description: "Vidéo", fetchInfo: "Analyser", duration: "Durée", convertTo: "Vers", videoDownloaderTitle: "Downloader" },
    hi: { title: "Video Suite", description: "वीडियो", fetchInfo: "विश्लेषण", duration: "अवधि", convertTo: "को", videoDownloaderTitle: "Downloader" },
    ru: { title: "Video Suite", description: "Видео", fetchInfo: "Анализ", duration: "Длительность", convertTo: "В", videoDownloaderTitle: "Downloader" }
};

export const SOCIAL_TOOLS_LABELS: Record<Language, any> = {
    pt: { instaFeedTitle: "Instagram Analytics", instaFeedDesc: "Análise avançada de posts com Gemini 3.", inputToken: "Token de Acesso (Graph API)", tokenPlaceholder: "Cole seu token aqui...", fetch: "Buscar Posts", loadDemo: "Carregar Demo", demoMode: "Modo demonstração ativo.", captionBtn: "Legenda IA", analyzeBtn: "Análise IA", noPosts: "Nenhum post encontrado.", viralCheckBtn: "Viral Audit", fbFeedTitle: "Facebook Hub", fbFeedDesc: "Análise de engajamento e alcance corporativo.", tiktokFeedTitle: "TikTok Trends", tiktokFeedDesc: "Insights de tendências e ganchos virais.", modal: { title: "Relatório Social", close: "Fechar", downloadPdf: "Baixar PDF" } },
    en: { instaFeedTitle: "Instagram Analytics", instaFeedDesc: "Advanced post analysis with Gemini 3.", inputToken: "Access Token (Graph API)", tokenPlaceholder: "Paste token here...", fetch: "Fetch Posts", loadDemo: "Load Demo", demoMode: "Demo mode active.", captionBtn: "AI Caption", analyzeBtn: "AI Analysis", noPosts: "No posts found.", viralCheckBtn: "Viral Audit", fbFeedTitle: "Facebook Hub", fbFeedDesc: "Corporate engagement and reach analysis.", tiktokFeedTitle: "TikTok Trends", tiktokFeedDesc: "Trend insights and viral hooks.", modal: { title: "Social Report", close: "Close", downloadPdf: "Download PDF" } },
    fr: { instaFeedTitle: "Instagram", analyzeBtn: "Analyse", modal: { title: "Rapport" } }, hi: { instaFeedTitle: "Instagram", analyzeBtn: "विश्लेषण", modal: { title: "रिपोर्ट" } }, ru: { instaFeedTitle: "Instagram", analyzeBtn: "Анализ", modal: { title: "Отчет" } }
};

export const EDITOR_LABELS: Record<Language, any> = {
    pt: { title: "Editor Pro", description: "Editor de Camadas Avançado", layer1: "Fundo", layer2: "Sobreposição", removeBg: "Remover Fundo IA", processing: "Editando...", tools: { move: "Mover", resize: "Redimensionar", wand: "Varinha" } },
    en: { title: "Editor Pro", description: "Advanced Layer Editor", layer1: "Background", layer2: "Overlay", removeBg: "AI Remove BG", processing: "Editing...", tools: { move: "Move", resize: "Resize", wand: "Wand" } },
    fr: { title: "Editor Pro", tools: {} }, hi: { title: "Editor Pro", tools: {} }, ru: { title: "Editor Pro", tools: {} }
};

export const PROMPT_TEMPLATES: PromptTemplates = { pt: {}, en: {}, fr: {}, hi: {}, ru: {} };
export const THEMES: Record<Theme, string> = { dark: "Escuro", light: "Claro", 'high-contrast': "Contraste", deuteranopia: "Daltônico (G)", protanopia: "Daltônico (R)", tritanopia: "Daltônico (B)" };
export const PARAMETER_DESCRIPTIONS: Record<string, string> = { task: "A tarefa principal que a IA deve executar.", role: "A persona ou cargo que a IA deve assumir.", background: "O contexto ou cenário do negócio.", length: "O tamanho e detalhamento da resposta esperada." };
