
import React, { useState, useRef } from 'react';
import { GoogleGenAI } from '@google/genai';
import Spinner from './Spinner';
import RealTimeAssetsModal from './RealTimeAssetsModal';
import { languageMap } from '../types';

interface InvestmentPortfolioAdvisorProps {
    labels: any;
    language: string;
}

const InvestmentPortfolioAdvisor: React.FC<InvestmentPortfolioAdvisorProps> = ({ labels, language }) => {
    const [profile, setProfile] = useState(labels.portfolioAdvisorProfiles[1]); // Default to Moderate
    const [timeHorizon, setTimeHorizon] = useState(labels.portfolioAdvisorTimeHorizons[2]); // Default to Long-Term
    const [amount, setAmount] = useState('');
    const [result, setResult] = useState('');
    const [isLoading, setIsLoading] = useState(false);
    const [error, setError] = useState('');
    const [isModalOpen, setIsModalOpen] = useState(false);
    const contentRef = useRef<HTMLDivElement>(null);

    const handleGenerate = async () => {
        setIsLoading(true);
        setError('');
        setResult('');

        try {
            const ai = new GoogleGenAI({ apiKey: process.env.API_KEY as string });
            
            let prompt = `Act as a professional financial advisor. Create a diversified investment portfolio suggestion for a "${profile}" investor with a "${timeHorizon}" time horizon.`;
            
            if (amount.trim()) {
                prompt += ` The user intends to invest ${amount} (in local currency). Please provide the specific monetary value for each asset allocation based on this total amount, in addition to percentages.`;
            } else {
                prompt += ` The user has not specified a total amount, so provide the allocation in percentages only.`;
            }

            prompt += `
The suggestion must include:
1. A clear asset allocation strategy with percentages (and values if applicable) for different classes (e.g., Fixed Income, Stocks, Real Estate, International Assets, Alternatives like crypto).
2. Examples of specific assets within each class.
3. A brief explanation of the rationale behind this allocation.
4. A mention of current major financial market trends relevant to this portfolio.
IMPORTANT: Include a disclaimer that this is not financial advice and past performance is not indicative of future results. Format the response using markdown.
IMPORTANT: Respond in ${languageMap[language as keyof typeof languageMap]}.`;
            
            const response = await ai.models.generateContent({
              model: 'gemini-2.5-flash',
              contents: prompt,
            });
            setResult(response.text);
        } catch (e) {
            console.error("Error generating portfolio:", e);
            setError(labels.error);
        } finally {
            setIsLoading(false);
        }
    };

    const handleDownloadPdf = () => {
        const printWindow = window.open('', '_blank');
        if (printWindow && contentRef.current) {
            printWindow.document.write(`
                <html>
                    <head>
                        <title>${labels.portfolioAdvisorTitle}</title>
                        <style>
                            body { font-family: Arial, sans-serif; padding: 20px; line-height: 1.6; color: #333; }
                            h1 { color: #4f46e5; border-bottom: 2px solid #eee; padding-bottom: 10px; }
                            .content { margin-top: 20px; }
                            .footer { margin-top: 40px; font-size: 12px; color: #666; text-align: center; border-top: 1px solid #eee; padding-top: 10px; }
                        </style>
                    </head>
                    <body>
                        <div class="header">
                            <h1>${labels.portfolioAdvisorTitle}</h1>
                            <p>Generated by Visionary AI Suite</p>
                        </div>
                        <div class="content">
                            ${contentRef.current.innerHTML}
                        </div>
                        <div class="footer">
                            &copy; ${new Date().getFullYear()} Visionary AI Suite. All rights reserved.
                        </div>
                        <script>
                            window.onload = function() { window.print(); }
                        </script>
                    </body>
                </html>
            `);
            printWindow.document.close();
        }
    };
    
    return (
        <section className="bg-gray-800/50 p-6 rounded-lg shadow-lg">
            <h3 className="text-2xl font-bold mb-2 text-indigo-400">{labels.portfolioAdvisorTitle}</h3>
            <p className="text-gray-400 mb-6">{labels.portfolioAdvisorDescription}</p>
            
            <div className="space-y-4">
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                    <div>
                        <label htmlFor="investor-profile" className="block text-sm font-medium text-gray-400 mb-2">{labels.portfolioAdvisorProfileLabel}</label>
                        <select
                        id="investor-profile"
                        value={profile}
                        onChange={(e) => setProfile(e.target.value)}
                        className="w-full bg-gray-800 border-gray-700 text-white rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500 transition duration-150 ease-in-out p-3 text-base"
                        >
                            {labels.portfolioAdvisorProfiles.map((p: string) => <option key={p} value={p}>{p}</option>)}
                        </select>
                    </div>
                     <div>
                        <label htmlFor="time-horizon" className="block text-sm font-medium text-gray-400 mb-2">{labels.portfolioAdvisorTimeHorizonLabel}</label>
                        <select
                        id="time-horizon"
                        value={timeHorizon}
                        onChange={(e) => setTimeHorizon(e.target.value)}
                        className="w-full bg-gray-800 border-gray-700 text-white rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500 transition duration-150 ease-in-out p-3 text-base"
                        >
                            {labels.portfolioAdvisorTimeHorizons.map((t: string) => <option key={t} value={t}>{t}</option>)}
                        </select>
                    </div>
                    <div>
                        <label htmlFor="investment-amount" className="block text-sm font-medium text-gray-400 mb-2">{labels.portfolioAdvisorAmountLabel || "Amount (Optional)"}</label>
                        <input
                            id="investment-amount"
                            type="number"
                            value={amount}
                            onChange={(e) => setAmount(e.target.value)}
                            placeholder={labels.portfolioAdvisorAmountPlaceholder || "e.g. 10000"}
                            className="w-full bg-gray-800 border-gray-700 text-white rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500 transition duration-150 ease-in-out p-3 text-base"
                        />
                    </div>
                </div>
                
                <div className="flex flex-col sm:flex-row gap-3">
                    <button
                        onClick={handleGenerate}
                        disabled={isLoading}
                        className="flex-1 flex items-center justify-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 disabled:bg-indigo-400 disabled:cursor-not-allowed transition-colors"
                    >
                        {isLoading ? <Spinner /> : null}
                        {isLoading ? labels.portfolioAdvisorButtonLoading : labels.portfolioAdvisorButton}
                    </button>
                    
                    <button
                        onClick={() => setIsModalOpen(true)}
                        className="flex-1 flex items-center justify-center px-4 py-2 border border-indigo-500/50 text-sm font-medium rounded-md shadow-sm text-indigo-300 bg-gray-800 hover:bg-gray-700 transition-colors"
                    >
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-5 h-5 mr-2">
                            <path strokeLinecap="round" strokeLinejoin="round" d="M2.25 18 9 11.25l4.306 4.307a11.95 11.95 0 0 1 5.814-5.519l2.74-1.22m0 0-5.94-2.28m5.94 2.28-2.28 5.941" />
                        </svg>
                        {labels.portfolioAdvisorShowTrending}
                    </button>
                </div>
            </div>
            
            {(result || error) && (
                <div className="mt-6 pt-4 border-t border-gray-700">
                    <div className="flex justify-between items-center mb-2">
                        <h4 className="text-lg font-semibold text-gray-200">{labels.resultTitle}</h4>
                        {result && (
                            <button 
                                onClick={handleDownloadPdf}
                                className="flex items-center text-sm text-indigo-400 hover:text-white transition-colors"
                            >
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-4 h-4 mr-1">
                                    <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 0 0 5.25 21h13.5A2.25 2.25 0 0 0 21 18.75V16.5M16.5 12 12 16.5m0 0L7.5 12m4.5 4.5V3" />
                                </svg>
                                {labels.downloadPdf || "Download PDF"}
                            </button>
                        )}
                    </div>
                    {error && <p className="text-red-400">{error}</p>}
                    {result && (
                        <div ref={contentRef} className="text-gray-300 prose prose-invert max-w-none bg-gray-900/50 p-4 rounded-md" dangerouslySetInnerHTML={{ __html: result.replace(/\n/g, '<br />') }} />
                    )}
                </div>
            )}

            <RealTimeAssetsModal 
                isOpen={isModalOpen} 
                onClose={() => setIsModalOpen(false)} 
                labels={labels} 
                language={language}
            />
        </section>
    );
};

export default InvestmentPortfolioAdvisor;
