
import React, { useState, useEffect, useRef } from 'react';
import { GoogleGenAI } from '@google/genai';
import Spinner from './Spinner';
import { languageMap } from '../types';

interface RealTimeAssetsModalProps {
    isOpen: boolean;
    onClose: () => void;
    labels: any;
    language: string;
}

const RealTimeAssetsModal: React.FC<RealTimeAssetsModalProps> = ({ isOpen, onClose, labels, language }) => {
    const [content, setContent] = useState('');
    const [isLoading, setIsLoading] = useState(false);
    const contentRef = useRef<HTMLDivElement>(null);

    useEffect(() => {
        const fetchTrends = async () => {
            if (!isOpen) return;
            setIsLoading(true);
            setContent('');

            try {
                const ai = new GoogleGenAI({ apiKey: process.env.API_KEY as string });
                const prompt = `Act as a financial market analyst. Provide a "Current Market Snapshot" listing examples of assets that are currently trending or popular in the financial world (focusing on the 2024-2025 context).
                
                Categorize them into:
                1. **High-Growth Stocks** (e.g., specific Tech/AI companies)
                2. **Cryptocurrencies** (major movers)
                3. **ETFs** (e.g., Clean Energy, Emerging Markets)
                4. **Commodities** (e.g., Gold, Lithium)
                
                For each category, list 2-3 specific real-world examples (tickers/symbols) and briefly explain *why* they are currently relevant or trending.
                
                Format the output using Markdown tables or clear bullet points.
                IMPORTANT: Start with a disclaimer that this is a snapshot of trends and not financial advice.
                IMPORTANT: Respond in ${languageMap[language as keyof typeof languageMap]}.`;

                const response = await ai.models.generateContent({
                    model: 'gemini-2.5-flash',
                    contents: prompt
                });
                setContent(response.text || "No trends available.");
            } catch (e) {
                console.error("Error fetching assets:", e);
                setContent("Failed to load trending assets. Please try again later.");
            } finally {
                setIsLoading(false);
            }
        };

        fetchTrends();
    }, [isOpen, language]);

    const handleDownloadPdf = () => {
        const printWindow = window.open('', '_blank');
        if (printWindow && contentRef.current) {
            printWindow.document.write(`
                <html>
                    <head>
                        <title>${labels.trendingAssetsModal.title}</title>
                        <style>
                            body { font-family: Arial, sans-serif; padding: 20px; line-height: 1.6; color: #333; }
                            h1 { color: #10b981; border-bottom: 2px solid #eee; padding-bottom: 10px; }
                            .disclaimer { background: #fffbeb; color: #92400e; padding: 10px; border: 1px solid #fcd34d; border-radius: 5px; margin-bottom: 20px; font-size: 0.9em; }
                            .content { margin-top: 20px; }
                            .footer { margin-top: 40px; font-size: 12px; color: #666; text-align: center; border-top: 1px solid #eee; padding-top: 10px; }
                        </style>
                    </head>
                    <body>
                        <div class="header">
                            <h1>${labels.trendingAssetsModal.title}</h1>
                            <p>Generated by Visionary AI Suite</p>
                        </div>
                        <div class="disclaimer">
                            ${labels.trendingAssetsModal.disclaimer}
                        </div>
                        <div class="content">
                            ${contentRef.current.innerHTML}
                        </div>
                        <div class="footer">
                            &copy; ${new Date().getFullYear()} Visionary AI Suite. All rights reserved.
                        </div>
                        <script>
                            window.onload = function() { window.print(); }
                        </script>
                    </body>
                </html>
            `);
            printWindow.document.close();
        }
    };

    if (!isOpen) return null;

    return (
        <div className="fixed inset-0 bg-black bg-opacity-75 flex items-center justify-center p-4 z-50" role="dialog" aria-modal="true">
            <div className="bg-gray-800 rounded-lg shadow-xl w-full max-w-3xl flex flex-col max-h-[90vh] border border-gray-700">
                <div className="flex justify-between items-center p-4 border-b border-gray-700 bg-gray-900/50 rounded-t-lg">
                    <h2 className="text-xl font-bold text-green-400 flex items-center gap-2">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6">
                            <path strokeLinecap="round" strokeLinejoin="round" d="M2.25 18 9 11.25l4.306 4.307a11.95 11.95 0 0 1 5.814-5.519l2.74-1.22m0 0-5.94-2.28m5.94 2.28-2.28 5.941" />
                        </svg>
                        {labels.trendingAssetsModal.title}
                    </h2>
                    <button onClick={onClose} className="text-gray-400 hover:text-white transition-colors">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6">
                            <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
                        </svg>
                    </button>
                </div>

                <div className="p-6 overflow-y-auto flex-grow bg-gray-900/50">
                    {isLoading ? (
                        <div className="flex flex-col items-center justify-center h-64">
                            <Spinner />
                            <p className="mt-4 text-gray-400 animate-pulse">{labels.trendingAssetsModal.loading}</p>
                        </div>
                    ) : (
                        <div ref={contentRef} className="prose prose-invert max-w-none text-gray-300">
                            <div className="bg-yellow-900/20 border border-yellow-700/50 p-3 rounded mb-4 text-xs text-yellow-200">
                                {labels.trendingAssetsModal.disclaimer}
                            </div>
                            <div dangerouslySetInnerHTML={{ __html: content ? content.replace(/\n/g, '<br />').replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>') : '' }} />
                        </div>
                    )}
                </div>

                <div className="p-4 border-t border-gray-700 bg-gray-800 rounded-b-lg flex justify-end gap-3">
                    <button 
                        onClick={onClose}
                        className="px-4 py-2 bg-gray-700 hover:bg-gray-600 text-white rounded-md text-sm font-medium transition-colors"
                    >
                        {labels.trendingAssetsModal.close}
                    </button>
                    {!isLoading && content && (
                        <button 
                            onClick={handleDownloadPdf}
                            className="px-4 py-2 bg-green-600 hover:bg-green-700 text-white rounded-md text-sm font-medium transition-colors flex items-center gap-2"
                        >
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-4 h-4">
                                <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 0 0 5.25 21h13.5A2.25 2.25 0 0 0 21 18.75V16.5M16.5 12 12 16.5m0 0L7.5 12m4.5 4.5V3" />
                            </svg>
                            {labels.trendingAssetsModal.downloadPdf}
                        </button>
                    )}
                </div>
            </div>
        </div>
    );
};

export default RealTimeAssetsModal;
