
import React, { useRef } from 'react';
import DOMPurify from 'dompurify';

interface SocialAnalysisModalProps {
    isOpen: boolean;
    onClose: () => void;
    content: string;
    labels: any;
}

const SocialAnalysisModal: React.FC<SocialAnalysisModalProps> = ({ isOpen, onClose, content, labels }) => {
    const contentRef = useRef<HTMLDivElement>(null);

    if (!isOpen) return null;

    // Securely sanitize content to prevent XSS from AI generated HTML/Markdown
    const sanitizedContent = DOMPurify.sanitize(content);

    const handleDownloadPdf = () => {
        const printWindow = window.open('', '_blank');
        if (printWindow && contentRef.current) {
            printWindow.document.write(`
                <html>
                    <head>
                        <title>${labels.modal.title}</title>
                        <style>
                            body { font-family: Arial, sans-serif; padding: 20px; line-height: 1.6; color: #333; }
                            h1 { color: #2563eb; border-bottom: 2px solid #eee; padding-bottom: 10px; }
                            pre { background: #f4f4f5; padding: 15px; border-radius: 5px; overflow-x: auto; white-space: pre-wrap; font-family: 'Courier New', Courier, monospace; }
                            .header { margin-bottom: 20px; }
                            .footer { margin-top: 40px; font-size: 12px; color: #666; text-align: center; border-top: 1px solid #eee; padding-top: 10px; }
                        </style>
                    </head>
                    <body>
                        <div class="header">
                            <h1>${labels.modal.title}</h1>
                            <p>Generated by Visionary AI Suite</p>
                        </div>
                        <div class="content">
                            ${contentRef.current.innerHTML}
                        </div>
                        <div class="footer">
                            &copy; ${new Date().getFullYear()} Visionary AI Suite. All rights reserved.
                        </div>
                        <script>
                            window.onload = function() { window.print(); }
                        </script>
                    </body>
                </html>
            `);
            printWindow.document.close();
        }
    };

    return (
        <div className="fixed inset-0 bg-black bg-opacity-75 flex items-center justify-center p-4 z-50 animate-fade-in" role="dialog" aria-modal="true">
            <div className="bg-gray-800 rounded-lg shadow-xl w-full max-w-3xl flex flex-col max-h-[90vh]">
                <div className="flex justify-between items-center p-4 border-b border-gray-700 bg-gray-900/50 rounded-t-lg">
                    <h2 className="text-xl font-bold text-white flex items-center gap-2">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6 text-blue-400">
                            <path strokeLinecap="round" strokeLinejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 0 0-3.375-3.375h-1.5A1.125 1.125 0 0 1 13.5 7.125v-1.5a3.375 3.375 0 0 0-3.375-3.375H8.25m0 12.75h7.5m-7.5 3H12M10.5 2.25H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 0 0-9-9Z" />
                        </svg>
                        {labels.modal.title}
                    </h2>
                    <button onClick={onClose} className="text-gray-400 hover:text-white transition-colors">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6">
                            <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
                        </svg>
                    </button>
                </div>

                <div className="p-6 overflow-y-auto flex-grow bg-gray-800">
                    <div ref={contentRef} className="prose prose-invert max-w-none">
                        <div className="bg-gray-900 p-4 rounded-lg border border-gray-700 whitespace-pre-wrap text-gray-300 font-mono text-sm">
                            {/* XSS Protection applied here */}
                            {sanitizedContent}
                        </div>
                    </div>
                </div>

                <div className="p-4 border-t border-gray-700 bg-gray-900/30 rounded-b-lg flex justify-end gap-3">
                    <button 
                        onClick={onClose}
                        className="px-4 py-2 bg-gray-700 hover:bg-gray-600 text-white rounded-md text-sm font-medium transition-colors"
                    >
                        {labels.modal.close}
                    </button>
                    <button 
                        onClick={handleDownloadPdf}
                        className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-md text-sm font-medium transition-colors flex items-center gap-2"
                    >
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-4 h-4">
                            <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 0 0 5.25 21h13.5A2.25 2.25 0 0 0 21 18.75V16.5M16.5 12 12 16.5m0 0L7.5 12m4.5 4.5V3" />
                        </svg>
                        {labels.modal.downloadPdf}
                    </button>
                </div>
            </div>
        </div>
    );
};

export default SocialAnalysisModal;